// common/enums/metodo-pago.enum.ts
export enum MetodoPagoEnum {
  EFECTIVO = 'EFECTIVO',
  TARJETA_CREDITO = 'TARJETA_CREDITO',
  TARJETA_DEBITO = 'TARJETA_DEBITO',
  TRANSFERENCIA = 'TRANSFERENCIA',
  QR = 'QR',
  DEPOSITO_BANCARIO = 'DEPOSITO_BANCARIO',
  MERCADO_PAGO = 'MERCADO_PAGO',
  YAPE = 'YAPE',
  PLIN = 'PLIN',
}
